//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blitzkrieg.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnsConfig
    {
        public long Id { get; set; }
        public string Host { get; set; }
        public Nullable<long> Port { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsUpdDisconnect { get; set; }
        public Nullable<long> UpdateFrequency { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    }
}
